/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CesiumError: typeof import('./components/cesium/CesiumError.vue')['default']
    CesiumViewer: typeof import('./components/cesium/CesiumViewer.vue')['default']
    IpAddressForm: typeof import('./components/IpAddressForm.vue')['default']
    IPAddressForm: typeof import('./components/IPAddressForm.vue')['default']
    IpAddressInfoCard: typeof import('./components/IpAddressInfoCard.vue')['default']
    IpAddressInfoToolbar: typeof import('./components/IpAddressInfoToolbar.vue')['default']
    IpAddressTrackerToolbar: typeof import('./components/IpAddressTrackerToolbar.vue')['default']
    LoadingIndicator: typeof import('./components/LoadingIndicator.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheMap: typeof import('./components/TheMap.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    Toaster: typeof import('./components/Toaster.vue')['default']
  }
}
